# Generated by Django 5.2.16 on 2026-07-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_document_ai_error_message_document_ai_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_from', to='documents.document')),
                ('related_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_to', to='documents.document')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'indexes': [models.Index(fields=['document', '-similarity_score'], name='relationshi_documen_ad528b_idx')],
                'unique_together': {('document', 'related_document')},
            },
        ),
    ]
