# Generated by Django 5.2.16 on 2026-07-14 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_ai_error_message_document_ai_processed_and_more'),
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrelationship',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documentrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Set only for manually-created relationships.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('similar', 'Similar'), ('referenced', 'Referenced'), ('same_category', 'Same Category'), ('same_keywords', 'Same Keywords'), ('duplicate', 'Duplicate'), ('manual', 'Manual')], default='similar', max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['relationship_type'], name='relationshi_relatio_a06a78_idx'),
        ),
    ]
