# Generated by Django 5.2.16 on 2026-07-13 09:52

import documents.models
import documents.storage
import documents.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('finance', 'Finance'), ('personal', 'Personal'), ('research', 'Research'), ('reports', 'Reports'), ('contracts', 'Contracts'), ('images', 'Images'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='cloudinary_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='relationship_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. "invoice, 2026, client-a"', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=documents.storage.get_document_storage, upload_to=documents.models.document_upload_path, validators=[documents.validators.validate_document_file]),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'category'], name='documents_d_owner_i_dd0bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'favorite'], name='documents_d_owner_i_eb9bb0_idx'),
        ),
    ]
