# Generated by Django 5.2.16 on 2026-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_category_document_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'AI Processing Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='detected_category',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('finance', 'Finance'), ('research', 'Research'), ('medical', 'Medical'), ('business', 'Business'), ('personal', 'Personal'), ('legal', 'Legal'), ('reports', 'Reports'), ('images', 'Images'), ('others', 'Others')], max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='document_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='last_ai_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_time',
            field=models.FloatField(default=0.0, help_text='AI pipeline duration in seconds'),
        ),
        migrations.AddField(
            model_name='document',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='document',
            name='similarity_score',
            field=models.FloatField(default=0.0, help_text='Highest similarity score against another document'),
        ),
        migrations.AddField(
            model_name='document',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
