# Generated by Django 5.2.16 on 2026-07-14 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_document_ai_error_message_document_ai_processed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('view', 'View'), ('download', 'Download'), ('delete', 'Delete'), ('rename', 'Rename'), ('favorite', 'Favorite'), ('ai_processing', 'AI Processing'), ('search', 'Search'), ('recommendation_click', 'Recommendation Click'), ('graph_interaction', 'Graph Interaction')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_968754_idx'), models.Index(fields=['user', 'event_type', '-created_at'], name='recommendat_user_id_8bff38_idx'), models.Index(fields=['document', 'event_type'], name='recommendat_documen_f96558_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('document_uploaded', 'Document Uploaded'), ('ai_completed', 'AI Completed'), ('ai_failed', 'AI Processing Failed'), ('relationship_discovered', 'Relationship Discovered'), ('document_deleted', 'Document Deleted'), ('favorite_updated', 'Favorite Updated')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='recommendat_user_id_fe5f67_idx')],
            },
        ),
    ]
